[package]
authors = [ "CoBloX developers <team@coblox.tech>" ]
categories = ["development-tools::testing"]
description = "Testcontainers, a library for integration-testing against docker containers from within Rust."
edition = "2018"
keywords = ["docker", "testcontainers"]
license = "MIT OR Apache-2.0"
name = "testcontainers"
repository = "https://github.com/testcontainers/testcontainers-rs"
version = "0.11.0"

[dependencies]
derivative = "2"
hex = "0.4"
hmac = "0.10"
log = "0.4"
rand = "0.7"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.9"

[dev-dependencies]
bitcoincore-rpc = "0.12"
postgres = "0.18"
pretty_env_logger = "0.4"
redis = "0.17"
mongodb = "1.0.0"
rusoto_core = "0.45"
rusoto_credential = "0.45"
rusoto_dynamodb = "0.45"
rusoto_sqs = "0.45"
spectral = "0.6"
reqwest = { version = "0.10", features = ["blocking"] }
json = "0.12"
tokio = { version = "0.2", features = ["macros"] }
env_logger = "0.8"
zookeeper = "0.5"
