[workspace]
resolver = "2"
members = [
    "testcontainers",
    "testimages",
]

[workspace.package]
authors = ["CoBloX developers <team@coblox.tech>"]
edition = "2021"
license = "MIT OR Apache-2.0"
rust-version = "1.63"

[workspace.dependencies]
testimages = { path = "testimages" }
