[package]
name = "testcontainers"
version = "0.12.0"
authors = [ "CoBloX developers <team@coblox.tech>" ]
categories = [ "development-tools::testing" ]
edition = "2018"
keywords = [ "docker", "testcontainers" ]
license = "MIT OR Apache-2.0"
repository = "https://github.com/testcontainers/testcontainers-rs"
rust-version = "1.46.0"
description = "A library for integration-testing against docker containers from within Rust."

[dependencies]
async-trait = { version = "0.1", optional = true }
bollard = { version = "0.11", optional = true }
bollard-stubs = "1.41"
futures = "0.3"
hex = "0.4"
hmac = "0.12"
log = "0.4"
rand = "0.8"
serde = { version = "1", features = [ "derive" ] }
serde_json = "1"
sha2 = "0.10"
tokio = { version = "1", features = [ "macros" ], optional = true }

[features]
experimental = [ "async-trait", "bollard", "tokio" ]

[dev-dependencies]
bitcoincore-rpc = "0.14"
json = "0.12"
lapin = "2.0.2"
mongodb = "2.0.0-beta"
orientdb-client = "0.6"
postgres = "0.19"
pretty_env_logger = "0.4"
rdkafka = "0.28"
redis = "0.21"
reqwest = { version = "0.11", features = [ "blocking" ] }
rusoto_core = "0.47"
rusoto_credential = "0.47"
rusoto_dynamodb = "0.47"
rusoto_sqs = "0.47"
spectral = "0.6"
tokio = { version = "1", features = [ "macros" ] }
tokio-amqp = "1.0.0"
zookeeper = "0.6"
