[package]
authors = [ "CoBloX developers <team@coblox.tech>" ]
categories = ["development-tools::testing"]
description = "Testcontainers, a library for integration-testing against docker containers from within Rust."
edition = "2018"
keywords = ["docker", "testcontainers"]
license = "MIT OR Apache-2.0"
name = "testcontainers"
repository = "https://github.com/testcontainers/testcontainers-rs"
version = "0.9.1"

[dependencies]
derivative = "1"
hex = "0.4"
hmac = "0.7"
log = "0.4"
rand = "0.7"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.8"

[dev-dependencies]
bitcoincore-rpc = "0.8.0-rc1"
postgres = "0.15"
pretty_env_logger = "0.3"
redis = "0.13"
rusoto_core = "0.41"
rusoto_credential = "0.41"
rusoto_dynamodb = "0.41"
rusoto_sqs = "0.41"
spectral = "0.6"
reqwest = "0.9"
json = "0.12.0"
