[package]
name = "testcontainers"
version = "0.12.0"
authors = [ "CoBloX developers <team@coblox.tech>" ]
categories = [ "development-tools::testing" ]
edition = "2018"
keywords = [ "docker", "testcontainers" ]
license = "MIT OR Apache-2.0"
repository = "https://github.com/testcontainers/testcontainers-rs"
description = "A library for integration-testing against docker containers from within Rust."

[dependencies]
async-trait = "0.1"
futures = "0.3"
hex = "0.4"
hmac = "0.10"
log = "0.4"
rand = "0.8"
serde = { version = "1", features = [ "derive" ] }
serde_json = "1"
sha2 = "0.10"
shiplift = { version = "0.7", default-features = false, features = [ "chrono", "unix-socket" ] }
tokio = { version = "1", features = [ "macros" ] }

[features]
experimental = [ ]

[dev-dependencies]
bitcoincore-rpc = "0.13"
json = "0.12"
lapin = "1.8.0"
mongodb = "2.0.0-beta"
orientdb-client = "0.6"
postgres = "0.19"
pretty_env_logger = "0.4"
rdkafka = "0.28"
redis = "0.21"
reqwest = { version = "0.11", features = [ "blocking" ] }
rusoto_core = "0.46"
rusoto_credential = "0.46"
rusoto_dynamodb = "0.46"
rusoto_sqs = "0.46"
spectral = "0.6"
tokio = { version = "1", features = [ "macros" ] }
tokio-amqp = "1.0.0"
zookeeper = "0.5"
