name: "Publish new release"

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  publish_release:
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release/') # only merged release branches must trigger this
    name: Publish release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout merge commit
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}

      - name: Extract version from branch name
        id: extract-version
        run: |
          BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
          VERSION=${BRANCH_NAME#release/}

          echo "::set-output name=version::$VERSION"

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Publish package
        run: cargo publish --token ${{ secrets.CRATES_IO_TOKEN }}

      - name: Create Release
        id: create-release
        uses: thomaseizinger/create-release@1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          target_commitish: ${{ github.event.pull_request.merge_commit_sha }}
          tag_name: ${{ steps.extract-version.outputs.version }}
          name: ${{ steps.extract-version.outputs.version }}
          draft: false
          prerelease: false

  merge_release_into_dev:
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release/') # only merged release branches must trigger this
    name: Merge release-branch back into dev
    runs-on: ubuntu-latest
    steps:
      - name: Extract version from branch name
        id: extract-version
        run: |
          BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
          VERSION=${BRANCH_NAME#release/}

          echo "::set-output name=version::$VERSION"

      - name: Create pull request for merging release-branch back into dev
        uses: thomaseizinger/create-pull-request@1.0.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          head: release/${{ steps.extract-version.outputs.version }}
          base: dev
          title: Merge release ${{ steps.extract-version.outputs.version }} into dev branch
          body: |
            This PR merges the release branch for ${{ steps.extract-version.outputs.version }} back into dev.
            This happens to ensure that the updates that happend on the release branch, i.e. CHANGELOG and manifest updates are also present on the dev branch.

